In [2]:
import numpy as np
import pandas as pd

In [3]:
firsttry = np.array([92.01,92.00,91.83,86.52,84.32,81.72,72.49,65.81,65.76])
secondtry = np.array([92.78,92.23,93.04,88.99,87.99,84.77,85.02,68.28,65.75])

In [4]:
firsttry-secondtry

array([-7.700e-01, -2.300e-01, -1.210e+00, -2.470e+00, -3.670e+00,
       -3.050e+00, -1.253e+01, -2.470e+00,  1.000e-02])

In [4]:
np.subtract(firsttry,secondtry)

array([-7.700e-01, -2.300e-01, -1.210e+00, -2.470e+00, -3.670e+00,
       -3.050e+00, -1.253e+01, -2.470e+00,  1.000e-02])

In [5]:
np.subtract(92.01,92.78)

-0.769999999999996

In [6]:
firsttry

array([92.01, 92.  , 91.83, 86.52, 84.32, 81.72, 72.49, 65.81, 65.76])

In [9]:
firsttry.dtype

dtype('float64')

In [1]:
92.01-92.78

-0.769999999999996

In [2]:
a = 92.01-92.78
-7.700e-01 == a

False

In [5]:
float_formatter = "{:.2f}".format

In [6]:
np.set_printoptions(formatter={'float_kind':float_formatter})

In [8]:
answer = secondtry -firsttry
answer

array([0.77, 0.23, 1.21, 2.47, 3.67, 3.05, 12.53, 2.47, -0.01])

In [49]:
acc = np.array([96.63,96.66,95.75,88.59,93.85,79.56,87.51,86.11,56.95])

In [26]:
d= np.array(["GBC","XGB","Random Forest","Kernel SVM","Decision Tree Classifier","Logistic Regression","SVC","KNN","Gaussian NB"])
models = pd.Series(d, name = "Models")
models


0                         GBC
1                         XGB
2               Random Forest
3                  Kernel SVM
4    Decision Tree Classifier
5         Logistic Regression
6                         SVC
7                         KNN
8                 Gaussian NB
Name: Models, dtype: object

In [36]:
thirdtry = np.array([92.65,92.84,93.29,89.03,87.80,84.73,84.97,68.89,65.75])
answer2 = thirdtry - firsttry
answer2 

array([0.64, 0.84, 1.46, 2.51, 3.48, 3.01, 12.48, 3.08, -0.01])

In [50]:
result1 = pd.Series(firsttry,name= "with outliers")
result2 = pd.Series(secondtry, name= "Removed outliers")
result3 = pd.Series(thirdtry, name = "Removed outliers, with account length bins")
difference = pd.Series(answer, name= "Difference between with outliers and Removed outliers")
difference2 = pd.Series(answer2, name = "Difference between with outliers and Removed outliers, with account length bins")
accuracy = pd.Series(acc, name="Accuracy,Removed outliers, with account length bins")
result1

0    92.01
1    92.00
2    91.83
3    86.52
4    84.32
5    81.72
6    72.49
7    65.81
8    65.76
Name: with outliers, dtype: float64

In [51]:
result2

0    92.78
1    92.23
2    93.04
3    88.99
4    87.99
5    84.77
6    85.02
7    68.28
8    65.75
Name: Removed outliers, dtype: float64

In [52]:
difference

0     0.77
1     0.23
2     1.21
3     2.47
4     3.67
5     3.05
6    12.53
7     2.47
8    -0.01
Name: Difference between with outliers and Removed outliers, dtype: float64

In [43]:
difference2

0     0.64
1     0.84
2     1.46
3     2.51
4     3.48
5     3.01
6    12.48
7     3.08
8    -0.01
Name: Difference between with outliers and Removed outliers, with account length bins, dtype: float64

In [53]:
improvement_df = pd.merge(models, result1, right_index = True, left_index = True) 
improvement_df

Models  with outliers
0                       GBC          92.01
1                       XGB          92.00
2             Random Forest          91.83
3                Kernel SVM          86.52
4  Decision Tree Classifier          84.32
5       Logistic Regression          81.72
6                       SVC          72.49
7                       KNN          65.81
8               Gaussian NB          65.76

In [54]:
improvement_df = pd.merge(improvement_df , result2, right_index = True, left_index = True) 
improvement_df

Models  with outliers  Removed outliers
0                       GBC          92.01             92.78
1                       XGB          92.00             92.23
2             Random Forest          91.83             93.04
3                Kernel SVM          86.52             88.99
4  Decision Tree Classifier          84.32             87.99
5       Logistic Regression          81.72             84.77
6                       SVC          72.49             85.02
7                       KNN          65.81             68.28
8               Gaussian NB          65.76             65.75

In [55]:
improvement_df = pd.merge(improvement_df , result3, right_index = True, left_index = True) 
improvement_df

Models  with outliers  Removed outliers  \
0                       GBC          92.01             92.78   
1                       XGB          92.00             92.23   
2             Random Forest          91.83             93.04   
3                Kernel SVM          86.52             88.99   
4  Decision Tree Classifier          84.32             87.99   
5       Logistic Regression          81.72             84.77   
6                       SVC          72.49             85.02   
7                       KNN          65.81             68.28   
8               Gaussian NB          65.76             65.75   

   Removed outliers, with account length bins  
0                                       92.65  
1                                       92.84  
2                                       93.29  
3                                       89.03  
4                                       87.80  
5                                       84.73  
6                                       84.97  
7                                       68.89  
8                                       65.75

In [56]:
improvement_df = pd.merge(improvement_df ,accuracy, right_index = True, left_index = True) 
improvement_df

Models  with outliers  Removed outliers  \
0                       GBC          92.01             92.78   
1                       XGB          92.00             92.23   
2             Random Forest          91.83             93.04   
3                Kernel SVM          86.52             88.99   
4  Decision Tree Classifier          84.32             87.99   
5       Logistic Regression          81.72             84.77   
6                       SVC          72.49             85.02   
7                       KNN          65.81             68.28   
8               Gaussian NB          65.76             65.75   

   Removed outliers, with account length bins  \
0                                       92.65   
1                                       92.84   
2                                       93.29   
3                                       89.03   
4                                       87.80   
5                                       84.73   
6                                       84.97   
7                                       68.89   
8                                       65.75   

   Accuracy,Removed outliers, with account length bins  
0                                              96.63    
1                                              96.66    
2                                              95.75    
3                                              88.59    
4                                              93.85    
5                                              79.56    
6                                              87.51    
7                                              86.11    
8                                              56.95

In [57]:
improvement_df = pd.merge(improvement_df,difference, right_index = True, left_index = True) 
improvement_df

Models  with outliers  Removed outliers  \
0                       GBC          92.01             92.78   
1                       XGB          92.00             92.23   
2             Random Forest          91.83             93.04   
3                Kernel SVM          86.52             88.99   
4  Decision Tree Classifier          84.32             87.99   
5       Logistic Regression          81.72             84.77   
6                       SVC          72.49             85.02   
7                       KNN          65.81             68.28   
8               Gaussian NB          65.76             65.75   

   Removed outliers, with account length bins  \
0                                       92.65   
1                                       92.84   
2                                       93.29   
3                                       89.03   
4                                       87.80   
5                                       84.73   
6                                       84.97   
7                                       68.89   
8                                       65.75   

   Accuracy,Removed outliers, with account length bins  \
0                                              96.63     
1                                              96.66     
2                                              95.75     
3                                              88.59     
4                                              93.85     
5                                              79.56     
6                                              87.51     
7                                              86.11     
8                                              56.95     

   Difference between with outliers and Removed outliers  
0                                               0.77      
1                                               0.23      
2                                               1.21      
3                                               2.47      
4                                               3.67      
5                                               3.05      
6                                              12.53      
7                                               2.47      
8                                              -0.01

In [58]:
improvement_df = pd.merge(improvement_df,difference2, right_index = True, left_index = True) 
improvement_df

Models  with outliers  Removed outliers  \
0                       GBC          92.01             92.78   
1                       XGB          92.00             92.23   
2             Random Forest          91.83             93.04   
3                Kernel SVM          86.52             88.99   
4  Decision Tree Classifier          84.32             87.99   
5       Logistic Regression          81.72             84.77   
6                       SVC          72.49             85.02   
7                       KNN          65.81             68.28   
8               Gaussian NB          65.76             65.75   

   Removed outliers, with account length bins  \
0                                       92.65   
1                                       92.84   
2                                       93.29   
3                                       89.03   
4                                       87.80   
5                                       84.73   
6                                       84.97   
7                                       68.89   
8                                       65.75   

   Accuracy,Removed outliers, with account length bins  \
0                                              96.63     
1                                              96.66     
2                                              95.75     
3                                              88.59     
4                                              93.85     
5                                              79.56     
6                                              87.51     
7                                              86.11     
8                                              56.95     

   Difference between with outliers and Removed outliers  \
0                                               0.77       
1                                               0.23       
2                                               1.21       
3                                               2.47       
4                                               3.67       
5                                               3.05       
6                                              12.53       
7                                               2.47       
8                                              -0.01       

   Difference between with outliers and Removed outliers, with account length bins  
0                                               0.64                                
1                                               0.84                                
2                                               1.46                                
3                                               2.51                                
4                                               3.48                                
5                                               3.01                                
6                                              12.48                                
7                                               3.08                                
8                                              -0.01

In [14]:
float_formatter(-7.700e-01)

'-0.77'

In [19]:
answer.dtype

dtype('float64')

In [20]:
type(answer)

numpy.ndarray

In [13]:
float_formatter(answer)

TypeError: unsupported format string passed to numpy.ndarray.__format__

In [16]:
float_formatter(answer)

TypeError: unsupported format string passed to numpy.ndarray.__format__

In [15]:
a = np.array([1, 2, 3, 4])

In [16]:
a + 1

array([2, 3, 4, 5])

In [17]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [18]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [19]:
a

array([1, 2, 3, 4])

In [20]:
a - b

array([-1.,  0.,  1.,  2.])

In [22]:
a.dtype

dtype('int32')